### PR TITLE
Bugfixes, python3 fixes, testing improvements

### PR DESCRIPTION
**Pull request by Daenyth**
- Support using `tox` for multi-environment testing
- Fix existing broken unit test
- Import cleanly under python3
- Tests pass under python3

### CODE REVIEW

**Comment by Daenyth** [comment]
Tox example output:

```
$ tox
GLOB sdist-make: /Users/daenyth/Curata/Python-ContextIO/setup.py
py27 inst-nodeps: /Users/daenyth/Curata/Python-ContextIO/.tox/dist/contextio-v1.11.2.zip
py27 installed: colorama==0.3.7,contextio==1.11.2,funcsigs==1.0.2,mock==1.3.0,nose==1.3.7,pbr==1.10.0,pluggy==0.3.1,py==1.4.31,python-termstyle==0.1.10,rauth==0.7.2,rednose==0.4.3,requests==2.11.1,six==1.10.0,tox==2.3.1,virtualenv==15.0.3
py27 runtests: PYTHONHASHSEED='2729886175'
py27 runtests: commands[0] | nosetests
nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module
...................................................................................................................................................
----------------------------------------------------------------------
Ran 147 tests in 0.196s

OK
py35 inst-nodeps: /Users/daenyth/Curata/Python-ContextIO/.tox/dist/contextio-v1.11.2.zip
py35 installed: colorama==0.3.7,contextio==1.11.2,mock==1.3.0,nose==1.3.7,pbr==1.10.0,pluggy==0.3.1,py==1.4.31,python-termstyle==0.1.10,rauth==0.7.2,rednose==0.4.3,requests==2.11.1,six==1.10.0,tox==2.3.1,virtualenv==15.0.3
py35 runtests: PYTHONHASHSEED='2729886175'
py35 runtests: commands[0] | nosetests
nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module
...................................................................................................................S...............................
----------------------------------------------------------------------
Ran 147 tests in 0.228s

OK (SKIP=1)
________________________________________________________________________________________________ summary _________________________________________________________________________________________________
  py27: commands succeeded
  py35: commands succeeded
  congratulations :)
```

**Comment by tantona** [comment]
Thank you for this PR sorry it took so long!

**Comment by Daenyth** [comment]
Merge conflicts should be fixed now, tox still runs clean

**Comment by Daenyth** [comment]
Thanks! I'd also suggest checking out pytest instead of nosetest - it should be more or less a drop-in replacement, barring swapping nose plugins for similar pytest ones. It's maintained, while nose isn't, and it's much more featureful

**Pull request merged**
